### PR TITLE
Henry: Slight rework to arrow velocity and mass

### PR DESCRIPTION
**Pull request by oliver-cool-beans**
Slight rework to the velocity, angle and mass of Henry's arrows

Accompanies PR:  https://github.com/Project-F/F.LF/pull/21

### CODE REVIEW

**Comment by tyt2y3** [comment]
Thank you for the contribution.
But why do we need to change henry.js?
All data files are converted as is from .dat to keep them 'original'.
What is the discrepancy and is it possible for us to handle it from F.LF?

**Comment by oliver-cool-beans** [comment]
Ah ok my mistake.
No worries. I can keep the character files original

I don't think its really essential to do this change anyway. I will have another test of this tomorrow night and make sure its working OK and this PR could be closed.
All could be done from F.LF

**Comment by tyt2y3** [comment]
Not at all. Thank you for your time indeed.
Actually several files (like `properties.js` and `soundpack.js`) were made up as they were hard coded in the program itself (I believe).

**Comment by oliver-cool-beans** [comment]
Closing, as this is not necessary

**Pull request closed without merging**
